ES6 and Modules
LethaboMot/Awesome-books pull request #6
Opened 2023-05-01 21:23 UTC by LethaboMot

in the project i:

- Made the modules
- Made set the packson.json
- Made `let` and `const` used correctly in the project

2023-05-02 11:27 UTC, FrederickMih requested changes
## Hi :raising_hand:  @LethaboMot, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



<img src="https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- PR is professional :+1: 
- Linter checks passed :heavy_check_mark: 


## Required Changes ♻️

- [ ] Based on the requirements of this project, your setup should have a `module` directory with some `.js` file. It is a good practice to split JavaScript files into modules that can be imported when needed. JavaScript modules allow you to break up your code into separate files. This makes it easier to maintain a code base. You can create modules for local storage, add and remove books, etc.


_Check the comments under the review._

## Optional suggestions

- Let's kindly ameliorate our commit messages. Some of your commit messages are not written in imperative tense or capitalized and some are not meaningful. Ex. @LethaboMot
[used the vars](https://github.com/LethaboMot/Awesome-books/pull/6/commits/8852bf1d72b059514a9ac9956e6828fe7a2f1f61)

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 11:27 UTC, FrederickMih commented on index.js
> +const timeNow = new Date();
- [ ] In the requirements of this project, we are requested to use [Luxon](https://github.com/moment/luxon/blob/master/docs/install.md) library to display the current date. The package should be added as a .js file to your project(in full or minified version). Let's kindly meet up with this requirements and move a step forward towards approval.

2023-05-03 10:12 UTC, emmiiorji requested changes
Hi @LethaboMot, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220871494-508d17d2-994a-4882-9dbe-dc118efcad37.gif'/>
</div>

 ## Good Highlights✔️

- App works as expected
- Good documentation in readme

 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 10:12 UTC, emmiiorji commented on luxon.js
As requested by the previous reviewer and as stated in the [project requirements](https://github.com/microverseinc/curriculum-javascript/blob/17555a4b0793b5065e3aeda6d2568fddd9c45330/books/books_with_es6.md?plain=1#L45), kindly divide your code into modules

2023-05-03 10:12 UTC, emmiiorji commented on luxon.js
> +document.getElementById('.date-time').innerHTML = d;
As pointed by the previous reviewer and mentioned in the [project requirements](https://github.com/microverseinc/curriculum-javascript/blob/17555a4b0793b5065e3aeda6d2568fddd9c45330/books/books_with_es6.md?plain=1#L53), kindly use the [Luxon](https://github.com/moment/luxon/blob/master/docs/install.md) library. See [Get the current date and time](https://github.com/moment/luxon/blob/master/docs/tour.md#get-the-current-date-and-time)

2023-05-03 20:13 UTC, AdnanOlarmmi requested changes
Hi @LethaboMot, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Nice design.
- Showed resourcefulness by appropriately using the Luxon library.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 20:13 UTC, AdnanOlarmmi commented on luxon.js
- [ ] [OPTIONAL] Nice one displaying time using Luxon, to ensure a more dynamic digital time... I'll suggest you update the time every second, using the `setTimeout` or `setTimeinterval` methods respectively.

2023-05-03 20:13 UTC, AdnanOlarmmi commented on index.js
> +    };
- [ ] As being said by previous reviewers, and I don't mean to bore you with this statement over and over again, kindly separate your functions into different modules or part, this will ensure you have a clean code, and you codebase will be easily susceptible to changes, whereby a developer or yourself wouldn't have to go through a long list of code, but rather straight up to the module. 😉

2023-05-04 03:14 UTC, andersonlebon approved these changes
## Hi @LethaboMot  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 08:45 UTC, merged